all:
	cd proj_beef && make flash && make rtt
	cd proj_cafe && make flash && make rtt
	cd proj_feed && make flash && make rtt
flash:
	cd proj_beef && make flash
	cd proj_cafe && make flash
	cd proj_feed && make flash
